
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ADDRESSES
export const CREATE_ADDRESSES_SUCCESS = "CREATE_ADDRESSES_SUCCESS";
export const DELETE_ADDRESSES_SUCCESS = "DELETE_ADDRESSES_SUCCESS";
export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
export const LIST_ADDRESSES_SUCCESS = "LIST_ADDRESSES_SUCCESS";
export const UPDATE_ADDRESSES_SUCCESS = "UPDATE_ADDRESSES_SUCCESS";

// CLIENTS
export const CREATE_CLIENTS_SUCCESS = "CREATE_CLIENTS_SUCCESS";
export const DELETE_CLIENTS_SUCCESS = "DELETE_CLIENTS_SUCCESS";
export const FINDBYUSERID_CLIENTS_SUCCESS = "FINDBYUSERID_CLIENTS_SUCCESS";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const LIST_CLIENTS_SUCCESS = "LIST_CLIENTS_SUCCESS";
export const UPDATE_CLIENTS_SUCCESS = "UPDATE_CLIENTS_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
